blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.blog_list, name='list'),
    path('', views.BlogListView.as_view(), name="list"),
    path('blog/create/', views.BlogCreateView.as_view(), name='create'),
    path('blog/<int:pk>/update',
         views.BlogUpdateView.as_view(), name="update"),
    path('blog/<int:pk>/delete',
         views.BlogDeleteView.as_view(), name="delete"),
    path('blog/<int:pk>/',
         views.BlogDetailView.as_view(), name='detail'),
]

financeblog/urls.py
"""financeblog URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('questions/', include('advice.urls', namespace='advice')),

    path('register/', account_views.register, name='register'),
    path('login/',
         auth_views.LoginView.as_view(template_name="account/login.html"),
         name="login"),
    path('logout/',
         auth_views.LogoutView.as_view(template_name="account/logout.html"),
         name="logout"),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name="account/password_reset.html"),
         name="password_reset"),
    path('password-reset/confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="account/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(
             template_name="account/password_reset_done.html"),
         name="password_reset_done"),
    path('password-reset/complete',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="account/password_reset_complete.html"),
         name="password_reset_complete"),

    path('profile/update', account_views.update_profile, name="update"),
    path('profile/<int:pk>', account_views.profile, name="profile"),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from django.core.validators import MinLengthValidator

content_validator = MinLengthValidator(
    limit_value=300, message="Content should be at least 300 characters long!")


class Blog(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField(validators=[content_validator])
    published = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={'pk': self.pk})

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
# from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    CreateView, DetailView, DeleteView, ListView, UpdateView)

from .models import Blog


# def blog_list(request):
#     blogs = Blog.objects.all()
#     return render(request, 'blog/list.html', {'blogs': blogs})


# def blog_detail(request, pk):
#     blog = get_object_or_404(Blog, pk=pk)
#     return render(request, 'blog/detail.html', {'blog': blog})


class BlogListView(ListView):
    model = Blog
    paginate_by = 3


class BlogDetailView(DetailView):
    model = Blog


class BlogCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Blog
    fields = ['title', 'content']
    success_message = "Blog Created Successfully!"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Blog
    fields = ['title', 'content']
    success_message = "Blog Updated Successfully!"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        """
        This method puts the conditional pass for the
        UserPassesTestMixin to only allow access to this view
        if the currently logged-in user is the author of the Post
        """
        blog = self.get_object()
        if self.request.user == blog.author:
            return True
        else:
            return False


class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    success_message = "Blog Deleted Successfully!"
    success_url = "/"

    def test_func(self):
        blog = self.get_object()
        if self.request.user == blog.author:
            return True
        else:
            return False

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

templates/blog/blog_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container bg-light p-5 mt-5 rounded ">
	<div class="row">
		<div class="col-12">
			<h2>Are you sure you want to delete the blog "<strong>{{ object.title }}</strong>"?</h2>
			<form method="POST">
				{% csrf_token %}
				<div class="form-group">
					<button class="btn btn-danger">Yes please.</button>
					<a class="btn btn-info" href="{% url 'blog:detail' object.pk %}">No, take
					me back</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock content %}

templates/blog/blog_detail.html
{% extends "base.html" %} 

{% block content %}
<div class="container blog bg-light p-5 mt-5 rounded">
    <div class="row">
        <div class="col-3 text-center">
            <a class="mugshot-container mb-1" href="{% url 'profile' blog.author.pk %}">
                {% if blog.author.profile.image %}
                <div class="mugshot-img mb-2" style="background-image:url({{ blog.author.profile.image.url }})"></div>
                {% endif %}
                <span>{{ blog.author.username }}</span>
            </a>
            <small class="text-muted">{{ blog.published|date:"d/m/Y h:i a" }}</small>
        </div>
        <div class="col-9 question-information pb-1">
            <h1 class="blog-card-title mb-3 font-weight-bold">{{ blog.title }}</h1>
            {% if request.user == blog.author %}
                <a class="btn btn-sm btn-primary" href="{% url 'blog:update' blog.pk %}">Update</a>
                <a class="btn btn-sm btn-danger" href="{% url 'blog:delete' blog.pk %}">Delete</a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-12 mt-5">
            <p class="line-height text-justify">{{ blog.content|linebreaks }}</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/blog_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="landing bg-dark">
	<div class="container">
		<div class="row align-items-center justify-content-center">
			<div class="col-sm-12 col-lg-6 text-center">
				<h1 class="text-white font-weight-bold display-3 mb-3">Blog</h1>
			</div>
		</div>
	</div>
</div>

<div class="container bg-light mt-n5 p-5 rounded ">
	<div class="row">
		<div class="col-12">
			<form method="POST">
				{% csrf_token %}
				{{ form|crispy }}
				<div class="form-group">
					<button class="btn btn-outline-dark">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock content %}

templates/blog/blog_list.html
{% extends "base.html" %} 

{% block content %}
<div class="landing bg-dark">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-sm-12 col-lg-6 text-center">
                <h1 class="text-white font-weight-bold display-3 mb-3">Finance blogs to help you succeed.</h1>
            </div>
        </div>
    </div>
</div>
<div class="container p-5 rounded">
    {% if object_list.count > 0 %}
    {% for blog in object_list %}
    <div class="row blog mb-5">
        <div class="col-lg-2 col-sm-12 text-center">
            <a class="mugshot-container mb-1" href="{% url 'profile' blog.author.pk %}">
                {% if blog.author.profile.image %}
                <div class="mugshot-img mb-2" style="background-image:url({{ blog.author.profile.image.url }})"></div>
                {% endif %}
                <span>{{ blog.author.username }}</span>
            </a>
            <small class="text-muted">{{ blog.published|date:"d/m/Y h:i a" }} </small>
        </div>
        <div class="col-lg-10 col-sm-12">
            <div class="blog-information">
                <h1 class="font-weight-bold mb-3">{{ blog.title }}</h1>
                <p>{{ blog.content|truncatewords:30 }}</p>
                <a href="{% url 'blog:detail' blog.pk %}" class="font-weight-bold mb-3 d-inline-block">Read More</a>
                <div class="update-edit">
                    {% if request.user.is_authenticated and request.user == blog.author %}
                    <a class="btn btn-sm btn-info" href="{% url 'blog:update' blog.pk %}">Update</a>
                    <a class="btn btn-sm btn-danger" href="{% url 'blog:delete' blog.pk %}">Delete</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- Pagination -->
    <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <div class="step-divider">
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            </div>
        {% endif %}
        
        <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
        
        {% if page_obj.has_next %}
            <div class="step-divider">
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            </div>
        {% endif %}
        </span>
    </div>
    {% else %}
        
    <h2 class="text-muted text-center">It's pretty lonely to have no blogs on a blogging site</h2>
    <p class="mt-3 h3 text-muted text-center">
        Add a blog? 
        <a href="{% url 'blog:create'
        %}">Click here</a>
    </p>
    {% endif %}
</div>
{% endblock content %}