advice/urls.py
from django.urls import path

from . import views

app_name = 'advice'

urlpatterns = [
    path('', views.QuestionListView.as_view(), name='list'),
    path('create/',
         views.QuestionCreateView.as_view(), name='create'),
    path('api/<int:pk>/', views.AdviceListView.as_view()),
    path('api/<int:pk>/create', views.AdviceCreateView.as_view()),
    path('<int:pk>/',
         views.QuestionDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/',
         views.QuestionDeleteView.as_view(), name='delete'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.blog_list, name='list'),
    path('', views.BlogListView.as_view(), name="list"),
    path('blog/create/', views.BlogCreateView.as_view(), name='create'),
    path('blog/<int:pk>/update',
         views.BlogUpdateView.as_view(), name="update"),
    path('blog/<int:pk>/delete',
         views.BlogDeleteView.as_view(), name="delete"),
    path('blog/<int:pk>/',
         views.BlogDetailView.as_view(), name='detail'),
]

financeblog/urls.py
"""financeblog URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('questions/', include('advice.urls', namespace='advice')),

    path('register/', account_views.register, name='register'),
    path('login/',
         auth_views.LoginView.as_view(template_name="account/login.html"),
         name="login"),
    path('logout/',
         auth_views.LogoutView.as_view(template_name="account/logout.html"),
         name="logout"),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name="account/password_reset.html"),
         name="password_reset"),
    path('password-reset/confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="account/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(
             template_name="account/password_reset_done.html"),
         name="password_reset_done"),
    path('password-reset/complete',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="account/password_reset_complete.html"),
         name="password_reset_complete"),

    path('profile/update', account_views.update_profile, name="update"),
    path('profile/<int:pk>', account_views.profile, name="profile"),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advice/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Question(models.Model):
    title = models.CharField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("advice:detail", kwargs={'pk': self.pk})


class Advice(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Advice by {self.author.username}"

advice/views.py
# from django.shortcuts import render
from django.contrib import messages
from django.views.generic import CreateView, DeleteView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils import formats

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.reverse import reverse

from .models import Advice, Question
from .serializers import AdviceCreateSerializer


class QuestionListView(ListView):
    model = Question
    paginate_by = 3
    ordering = ['-published']


class QuestionCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Question
    fields = ['title']
    success_message = "Question created successfully!"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class QuestionDetailView(DetailView):
    model = Question


class QuestionDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Question
    success_message = "Question Deleted Successfully!"
    success_url = "/questions/"

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.author:
            return True
        else:
            return False

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)


class AdviceListView(APIView):
    def get(self, request, pk=None):
        # Retrieve all instances of the Advice model that belongs to a question
        queryset = Advice.objects.all().filter(
            question_id=pk).order_by('-published')
        data_to_return = []

        for advice in queryset:
            username = advice.author.username
            user_url = request.build_absolute_uri(
                reverse('profile', args=[advice.author.pk]))
            user_image = request.build_absolute_uri(
                advice.author.profile.image.url)
            content = advice.content
            published = formats.date_format(
                advice.published, "SHORT_DATETIME_FORMAT")

            # Create instance of the Advice that'll be sent back to the URL
            instance = {
                'username': username,
                'user_url': user_url,
                'user_image': user_image,
                'content': content,
                'published': published
            }
            data_to_return.append(instance)
        # Returns data thro' the Response method after conversion to JSON obj
        return Response(data_to_return)


class AdviceCreateView(APIView):
    def post(self, request, pk=None):
        if request.user.is_authenticated:
            # pass in the user submitted data from the request
            serializer = AdviceCreateSerializer(data=request.data)
            if serializer.is_valid():
                user = request.user
                try:
                    question = Question.objects.get(pk=pk)
                except Question.DoesNotExist:
                    return Response({"error": "Question does not exist."},
                                    status=status.HTTP_400_BAD_REQUEST)
                advice = Advice.objects.create(
                    content=serializer.validated_data["content"],
                    author=user, question=question)
                advice.save()
                # returns a JSON/Dict object after save
                data_to_return = {
                    "username": advice.author.username,
                    "user_url": reverse("profile",
                                        args=[advice.author.pk],
                                        request=request),
                    "user_image": request.build_absolute_uri(
                        advice.author.profile.image.url),
                    "content": advice.content,
                    "published": formats.date_format(advice.published,
                                                     "SHORT_DATETIME_FORMAT")
                }
                return Response(data_to_return, status=status.HTTP_201_CREATED)
            else:
                return Response(status=status.HTTP_400_BAD_REQUEST)
        else:
            return Response(status.HTTP_401_UNAUTHORIZED)

templates/advice/question_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container bg-light p-5 mt-5 rounded ">
	<div class="row">
		<div class="col-12">
			<h2>Are you sure you want to delete the question "<strong>{{ question.title }}</strong>"?</h2>
			<form method="POST">
				{% csrf_token %}
				<div class="form-group">
					<button class="btn btn-danger">Yes please.</button>
					<a class="btn btn-info" href="{% url 'advice:detail' question.pk %}">No, take
					me back</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock content %}

templates/advice/question_detail.html
{% extends "base.html" %} 

{% block content %}
<div class="container blog bg-light p-5 mt-5 rounded">
    <div class="row">
        <div class="col-3 text-center">
            <a class="mugshot-container mb-1" href="{% url 'profile' question.author.pk %}">
                {% if question.author.profile.image %}
                <div class="mugshot-img mb-2" style="background-image:url({{ question.author.profile.image.url }})"></div>
                {% endif %}
                <span>{{ question.author.username }}</span>
            </a>
            <small class="text-muted">{{ question.published|date:"d/m/Y h:i a" }}</small>
        </div>
        <div class="col-9 question-information pb-1">
            <div class="question">
                <div class="question-mark">
                    <span>Q:</span>
                </div>
                <div class="question-content">
                    <h3 class="mb-0">{{ question.title }}</h3>
                </div>
            </div>
            {% if request.user == question.author %}
            <div class="pl-2">
                <a class="btn btn-sm btn-danger" href="{% url 'advice:delete' question.pk %}">Delete</a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <div class="question-detail-container">
                <div class="answers-container">
                    <span id="answer-above"></span>
                    <p class="loading-comment animate text-center">loading advices...</p>
                    {% if request.user.is_authenticated %}
                    <form class="post-answer-form">
                        <div class="form-group">
                            <label for="answer" class="answer-heading">Post an advice</label>
                            <textarea class="form-control advice-form mb-2" name="answer" id="answer" rows="5"></textarea>
                            <button class="btn btn-primary" type="submit" id="post-comment">Submit</button>
                        </div>
                        <p class="text-danger font-weight-bold" id="form-error"></p>
                    </form>
                    {% else %}
                    <p class="answer-heading"><a href="{% url 'login' %}">Login</a> to post an
                    advice</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block js %}
<script>
// ready ensures code runs after the document has been fully loaded
$(document).ready(function() {
    // This function runs once and fetches the advices of this specific question.
    function fetchAdvicesUpdateUI() {
        // Fetching Data from our own REST API
        // the fetch() func is used to make HTTP requests
        fetch("/questions/api/{{question.id}}")
        // returns a response thro' which we get our JSON data
        .then(res => res.json())
        // use the returned data to display advice on the page
        .then(data => {
            let answers = []
            // Loop over the data returned from the api.
            for(var i = 0; i < data.length; i++) {
                // Constructing the markup from the data returned from API.
                var answer = [
                    "<div class='answer'><div class='answer-by'>",
                    "<a class='mugshot-container mb-1' href='",
                    data[i].user_url,
                    "'> <div class='mugshot-img-sm mb-2' style='background-image:url(",
                    data[i].user_image,
                    ")'></div><span>",
                    data[i].username,
                    "</span></a> <small class='text-muted'>",
                    data[i].date_published,
                    "</small></div><div class='answer-content'> <p>",
                    data[i].content,
                    "</p></div></div>"
                ]
                answers.push(answer.join(""))
            }
            if( answers.length < 1) {
                answers = ['<p class="no-answer">No answers posted to this thread yet!</p>']
            } else {
                answers.unshift('<h3 class="answer-heading" id="answer-here">Answers:</h3>')
            }
            // Loop over the advices array and push it to our html document.
            for(var i = 0; i < answers.length; i++) {
                $("#answer-above").before(answers[i])
            }
            // Hide the loading advices message.
            $(".loading-comment").css("display", "none")
        })
    }
    // Load the advices once on page was loaded.
    fetchAdvicesUpdateUI()

    // Code for creating and submitting advice to a question.
    // Whenever form is submitted, execute following method.
    $(".post-answer-form").on("submit", function (e) {
        // prevents the default behavior of the submit button
        e.preventDefault()
        // Pass the content from the input box
        postAdvice($('.advice-form').val())
    })
    function postAdvice(content) {
        // Check if answer was empty and return if true.
        if (content.length === 0) {
            $("#form-error").text("Can't be empty!")
            $("#form-error").css("display", "block")
            return;
        }
        $("#form-error").css("display", "none")
        // Hide button interaction
        $("#post-comment").text("Wait...").attr('disabled', true);
        // Construct data to send to our REST API
        var mydata = {
            'content': content,
        };
        // Insert question-id and user-token for the POST request.
        fetch('/questions/api/{{question.id}}/create', {
            // sends a POST request to the api path above
            method: 'POST',
            headers: {
                // tells the backend that the body will be of type JSON
                'Content-Type': 'application/json',
                // Get the csrf token and attach to our request
                'X-CSRFTOKEN': Cookies.get('csrftoken')
            },
            // data we want to send to api after converting to json string
            body: JSON.stringify(mydata)
        })
        // API returns the newly created Advice instance
        .then(res => res.json())
        .then(data => {
            // Constructing markup in array from data received.
            var answer = [
                "<div class='answer new-answer'><div class='answer-by'>",
                "<a class='mugshot-container mb-1' href='",
                data.user_url,
                "'> <div class='mugshot-img-sm mb-2' style='background-image:url(",
                data.user_image,
                ")'></div><span>",
                data.username,
                "</span></a> <small class='text-muted'>",
                data.date_published,
                "</small></div><div class='answer-content'> <p>",
                data.content,
                "</p></div></div>"
            ]
            // If answers exist, post before the latest answer (at the top).
            if ($(".answer").length > 0) {
                $("#answer-here").after(answer.join(''));
            } else {
                // If this is the first anser, this will be posted before the identifier.
                $("#answer-above").after('<h3 class="answer-heading" id="answer-here">Answers:</h3>')
                $("#answer-here").after(answer.join(''))
                $(".no-answer").css("display", "none")
            }
            // Updating button to 'clickable' and changing text back to "Submit".
            $("#post-comment").text("Submit").attr('disabled', false);
            // Clear the input field.
            $('.advice-form').val("");
            // Scroll to answer we just saved and the api returned.
            $("html, body").animate({
                scrollTop: $("#answer-here").offset().top
            }, 500);
            // Unfocus the submit button.
            $("#post-comment").blur();
        })
        .catch(err => console.log(err))
    }
})
</script>
{% endblock js %}


templates/advice/question_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="landing bg-dark">
	<div class="container">
		<div class="row align-items-center justify-content-center">
			<div class="col-sm-12 col-lg-6 text-center">
				<h1 class="text-white font-weight-bold display-3 mb-3">Have a Question?</h1>
			</div>
		</div>
	</div>
</div>

<div class="container bg-light mt-n5 p-5 rounded ">
	<div class="row">
		<div class="col-12">
			<form method="POST">
				{% csrf_token %}
				{{ form|crispy }}
				<div class="form-group">
					<button class="btn btn-outline-dark">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock content %}

templates/advice/question_list.html
{% extends "base.html" %} 

{% block content %}
<div class="landing bg-dark">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-sm-12 col-lg-6 text-center">
                <h1 class="text-white font-weight-bold display-3 mb-3">Help others succeed in finance.</h1>
            </div>
        </div>
    </div>
</div>
<div class="container p-5 rounded">
    {% if object_list.count > 0 %}
    {% for question in object_list %}
    <div class="row blog mb-5">
        <div class="col-lg-2 col-sm-12 text-center">
            <a class="mugshot-container mb-1" href="{% url 'profile' question.author.pk %}">
                {% if question.author.profile.image %}
                <div class="mugshot-img mb-2" style="background-image:url({{ question.author.profile.image.url }})"></div>
                {% endif %}
                <span>{{ question.author.username }}</span>
            </a>
            <small class="text-muted">{{ question.published|date:"d/m/Y h:i a" }} </small>
        </div>
        <div class="col-lg-10 col-sm-12">
            <div class="blog-information">
                <h3 class="font-weight-bold mb-3">{{ question.title }}</h3>
                <a href="{% url 'advice:detail' question.pk %}" class="font-weight-bold mb-3 d-inline-block">Read Thread</a>
                <div class="update-edit">
                    {% if request.user.is_authenticated and request.user == question.author %}
                    <a class="btn btn-sm btn-danger" href="{% url 'advice:delete' question.pk %}">Delete</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- Pagination -->
    <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <div class="step-divider">
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            </div>
        {% endif %}
        
        <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
        
        {% if page_obj.has_next %}
            <div class="step-divider">
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            </div>
        {% endif %}
        </span>
    </div>
    {% else %}
        
    <h2 class="text-muted text-center">No queries posted yet...</h2>
    <p class="mt-3 h3 text-muted text-center">
        Ask a question? 
        <a href="{% url 'advice:create' %}">Click here</a>
    </p>
    {% endif %}
</div>
{% endblock content %}